# ASP.NET Core
# Build and test ASP.NET Core projects targetting .NET Core.

trigger:
- main

pool: 
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'